version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: house-router:api
    container_name: api
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/api
